function mexbuild(pathToTTK)

mex('MorseSmale.cpp', ...
    [fullfile(pathToTTK, 'lib/ttk/') '*.a'], ...
    '-R2018a', ...
    '-O', ...
    '-g', ...
    ['-I' fullfile(pathToTTK, 'include/ttk/base')], ...
    '-I/usr/local/include');
end