function mexbuild(pathToTTK)

mex('MorseSmale.cpp', ...
    [fullfile(pathToTTK, 'lib/') '*.dylib'], ...
    '-R2018a', ...
    '-O', ...
    '-g', ...
    ['LDFLAGS=$LDFLAGS -Wl,-rpath,' fullfile(pathToTTK, 'lib')], ...
    ['-I' fullfile(pathToTTK, 'include/ttk/base')], ...
    '-I/usr/local/include');
end